[package]
name = "test2"
version = "0.1.0"
authors = ["Tyler Liu<tylerliu@noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
